---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: fio-job-config
data:
  fio.job: |-
    [global]
    ioengine=psync
    direct=1
    buffered=0
    size=100M
    iodepth=4
    numjobs=1
    group_reporting
    refill_buffers
    rwmixread=50
    norandommap
    randrepeat=0
    percentage_random=50
    bs=512K
    buffer_compress_percentage=50
    rw=randrw
    [testjob]
...
