---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: fiobench-rwx
  labels:
    app: fiobench-rwx
spec:
  replicas: 3
  selector:
    app: fiobench-rwx
    deploymentconfig: fiobench-rwx
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: fiobench-rwx
        deploymentconfig: fiobench-rwx
    spec:
      containers:
      - name: fiobench-rwx
        image: fiobench:latest
        command: ["fio.sh"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
        - name: webroot-mount
          mountPath: /output
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config
      - name: fio-data
        persistentVolumeClaim:
          claimName: fio-claim
      - name: webroot-mount
        persistentVolumeClaim:
          claimName: webroot
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - fiobench-rwx
      from:
        kind: ImageStreamTag
        name: fiobench:latest
    type: ImageChange
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim
spec:
#  storageClassName: ocs-storagecluster-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 10Gi
...
