---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiobench-rwo
spec:
  serviceName: fiobench-rwo
  replicas: 60
  selector:
    matchLabels:
      app: fiobench-rwo
  template:
    metadata:
      labels:
        app: fiobench-rwo
    spec:
      containers:
      - name: fiobench-rwo
        image: fiobench
        command: ["fio.sh"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
        - name: webroot-mount
          mountPath: /output
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config
      - name: webroot-mount
        persistentVolumeClaim:
          claimName: webroot
  volumeClaimTemplates:
  - metadata:
      name: fio-data
    spec:
#      storageClassName: ocs-storagecluster-ceph-rbd
#      storageClassName: fake-fs-sc
      storageClassName: ibm-spectrum-scale-light-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
#          storage: 1Gi
...
