---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: fiobench-rwx
  labels:
    app: fiobench-rwx
spec:
  replicas: 1
  selector:
    app: fiobench-rwx
    deploymentconfig: fiobench-rwx
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: fiobench-rwx
        deploymentconfig: fiobench-rwx
    spec:
      containers:
      - name: fiobench-rwx
        image: fiobench:latest
        command: ['cd $NODE_NAME && fio.sh']
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data-0
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: fio-data-1
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: fio-data-2
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: fio-data-3
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: fio-data-4
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: fio-data-5
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: fio-data-6
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: fio-data-7
          mountPath: /scratch/x29wkr1.bt23005.pbm.ihost.com
        - name: webroot-mount
          mountPath: /output
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config
      - name: fio-data-0
        persistentVolumeClaim:
          claimName: fio-claim-0
      - name: fio-data-1
        persistentVolumeClaim:
          claimName: fio-claim-1
      - name: fio-data-2
        persistentVolumeClaim:
          claimName: fio-claim-2
      - name: fio-data-3
        persistentVolumeClaim:
          claimName: fio-claim-3
      - name: fio-data-4
        persistentVolumeClaim:
          claimName: fio-claim-4
      - name: fio-data-5
        persistentVolumeClaim:
          claimName: fio-claim-5
      - name: fio-data-6
        persistentVolumeClaim:
          claimName: fio-claim-6
      - name: fio-data-7
        persistentVolumeClaim:
          claimName: fio-claim-7
      - name: webroot-mount
        persistentVolumeClaim:
          claimName: webroot
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - fiobench-rwx
      from:
        kind: ImageStreamTag
        name: fiobench:latest
    type: ImageChange
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-0
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-1
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-2
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-3
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-4
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-5
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-6
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-7
spec:
#  storageClassName: ocs-storagecluster-cephfs
#  storageClassName: fake-fs-sc
  storageClassName: scale-csi-ess3500
  accessModes:
  - ReadWriteMany
  resources:
    requests:
#      storage: 50Ti
      storage: 100Gi
...
